server.port=8081

spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:paysense}
spring.datasource.username=${DB_USERNAME:paysense}
spring.datasource.password=${DB_PASSWORD:paysense123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:8ae68032d8471e89ceb64267b2d41bf63675fcd6c478676f2d5930e167c13ac3}
app.jwt.expiration=${JWT_ACCESS_EXPIRY_MS:900000}
app.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRY_MS:604800000}
app.payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
